### ISSUE TITLE
powerplatform_managed_environment resource

### ISSUE THREAD

**Issue by mattdot** [microsoft/terraform-provider-power-platform#104]
## Description

Enable the ability to create a [managed environment](https://learn.microsoft.com/en-us/power-platform/admin/managed-environment-enable).  May need to spike to see if this should be an attribute of the environment resource or its own separate resource?

### Resource

- Resource Name: `powerplatform_environment` or `powerplatform_managed_environment`
- API documentation: see BAPI documentation or powershell cli
- Estimated complexity/effort: moderate
- Related resources/data sources: 
  - `powerplatform_environment` resource

### Potential Terraform Configuration

```hcl
# Sample Terraform config that describes how the new resource might look.

resource "powerplatform_environment" "my_env" {
  name = "example"
  managed = true
  ...
}
```

OR

```hcl
resource "powerplatform_environment" "my_env" {
  name = "example"
  ...
}

resource "powerplatform_managed_environment" "my_managed_environment" {
  environment_id = my_env.id
}

```

## UI Process

To convert an environment to be a managed environment you need the following steps:
- Sign and open the Power Platform admin center.
- Go to the “environments” tab and select it, you will see a table with the environments, and you can verify if the environment is managed or not in the Managed column.
- Select the environment that you want to convert to a managed environment.
- Select the “Enable Managed Environments” tab on the top of the environment’s configuration page.

![Image](https://github.com/microsoft/terraform-provider-power-platform/assets/15805460/91f2cc05-fe6f-41d3-ab08-ee96b9411e18)

## Considerations

Licensing: Once enabled, users will need a Power Apps, Power Automate, or Dynamics 365 license with premium use rights to use the respective resources in this environment. [Learn more](https://go.microsoft.com/fwlink/?linkid=2211914)

## Properties Description to convert a Managed environment
Properties description to convert a unmanaged environment to be managed should consider the following properties:

- Limit sharing
- Solution checker enforcement (preview)
- Usage insights
- Maker welcome content (preview)

Note: Data Policies, the data policy section only provides a link for Power Platform Admins to see the data policies for this environment, is an informative section, will not be required for the PP TF Provider.

### Configuration properties for managed environments

![Image](https://github.com/microsoft/terraform-provider-power-platform/assets/15805460/4eedd5a6-d0f7-4329-ad07-db8abc79642a)

### Limit sharing
Help reduce risk by limiting how widely canvas apps can be shared. [Learn more](https://go.microsoft.com/fwlink/?linkid=2211538)
Default Configuration:		Don’t set limits (default)
Alternative configuration:	Exclude sharing with security groups.
	Exclude sharing with security groups is a second level option that ask for limits:
Limit total individuals who can share to: No limit (Default), alternatively user can set a value from 1 to 99.

### Solution checker enforcement (preview)
Automatically verify solution checker results for security and reliability issues before solution import. [Learn more](https://go.microsoft.com/fwlink/?linkid=2207838)
User can choose from 3 options:
•	None, Turn off solution checker verification during solution import. You can continue to manually review the results in the solution explorer.
•	Warm (default value), Check for security and reliability issues in the solution checker results, but do not block solution import for any issues.
•	Block, Check for security and reliability issues in the solution checker results and block the solution from being imported if critical issues are found.

PP admin can choose if the solution checker will send emails only when a solution is blocked:
•	Send emails only when a solution is blocked. If unchecked, you’ll also get emails when there are warnings, (default is disabled).
Also, PP admin can choose to exclude a rule.

### Usage insights
Get adoption insights, like top apps and flows, in this environment. [Learn more](https://go.microsoft.com/fwlink/?linkid=2211177)
PP Admin can enable or disable the: 
•	Include insights for this environment in the weekly email digest, (default is disabled).
Note: Weekly digest is a Tennant Settings list of emails, admin emails can be added to that list.
 
### Maker welcome content (preview)
•	First-time Power Apps makers will see this page in the Studio. [Learn more](https://go.microsoft.com/fwlink/?linkid=2223701)
Power Platform Admins can fill in the welcome message in a text box with a maximum of 1500characters.
•	Learn more URL.
Power Platform Admins can paste a learn more URL.
 

### Data policies (informative)
Help safeguard your organizational data by limiting the connectors available. [Learn more](https://go.microsoft.com/fwlink/?linkid=2211178)
The data policy section only provides a link for Power Platform Admins to see the data policies for this environment, is an informative section, will not be required for the PP TF Provider.

## Definition of Done

- [ ] Data Transfer Objects (dtos)
- [ ] Data Client functions
- [ ] Resource Implementation
- [ ] Resource Added to Provider
- [ ] Unit Tests for Happy Path
- [ ] Unit Tests for error path
- [ ] Acceptance Tests
- [ ] Example in the /examples folder
- [ ] Schema Documentation in code
- [ ] Updated auto-generated provider docs with `make docs`

## Contributions

Do you plan to raise a PR to address this issue?  YES

See the [contributing guide](/CONTRIBUTING.md?) for more information about what's expected for contributions.

```[tasklist]
### Tasks
```
