### ISSUE TITLE
All delete operations should wait for lifecycle operation to finish

### ISSUE THREAD

**Issue by mawasile** [microsoft/terraform-provider-power-platform#114]
## Describe the bug

Currently we just "fire and forget" delete operation on all resources, where BAPI actually returns location header with operation lifecycle URL to monitor the operation.

## Contribution
Do you plan to raise a PR to address this issue?
- [x ] Yes
- [ ] No

```[tasklist]
### Tasks
- [x] fix delete for environment
- [x] fix delete for dlp policy
- [ ] fix delete for managed environment
- [x] if possible, make operation lifecycle operation wait reusable method in base api struct
```
