### ISSUE TITLE
Security review

### ISSUE THREAD

**Issue by leighatami** [microsoft/terraform-provider-power-platform#125]
Security review needed for go-public. Specifically, we need:

```[tasklist]
### Tasks
- [ ] Threat Model
- [x] Secret Scanning Enabled (GitHub Advanced Security)
- [x] Secret Store Configured (GitHub Encrypted Secrets)
- [x] Secrets Management (GitHub encrypted secrets)
```
