### ISSUE TITLE
As a contributor, I want clear developer documentation

### ISSUE THREAD

**Issue by mattdot** [microsoft/terraform-provider-power-platform#27]
```[tasklist]
### Tasks
- [x] documentation on using the devcontainer
- [x] documentation on building & running the provider locally
- [x] documentation on debugging the provider
- [x] documentation on writing and running tests
- [x] documentation on generating documentation
- [x] documentation on what's expected in a PR
```
