### ISSUE TITLE
As a maintainer, I want to create releases of the provider

### ISSUE THREAD

**Issue by mattdot** [microsoft/terraform-provider-power-platform#28]
```[tasklist]
### Tasks
- [x] Trigger a release by tagging main branch with v#.#.#
- [x] Automatic generation of release notes
- [x] Build provider for linux, debian, and windows
- [x] Attach packaged binaries to the release
- [x] Sign the release with GPG
```
