### ISSUE TITLE
Support Policy

### ISSUE THREAD

**Issue by mattdot** [microsoft/terraform-provider-power-platform#4]
As a Terraform user, I want clear understanding of how this provider is supported.

Need to update the /SUPPORT.md file with the appropriate support information.  See the current markdown file for sections that need to be completed and/or edited
```[tasklist]
### Tasks
- [ ] update the /SUPPORT.md file with the appropriate support information. See the current markdown file for sections that need to be completed and/or edited
- [ ] Complete the supportability checklist
- [ ] Onboard to CSS support?
- [ ] https://github.com/microsoft/terraform-provider-power-platform/issues/125
```
