### ISSUE TITLE
SAP Connector Guide

### ISSUE THREAD

**Issue by mattdot** [microsoft/terraform-provider-power-platform#55]
As a user, I want a quick start guide that shows me how to use terraform to create and configure a connection from Power Platform to SAP via the data gateway. 

- [ ] Implement the infrastructure of the [SAP ERP Connector and Data Gateway from this article](https://powerapps.microsoft.com/en-us/blog/introducing-the-sap-erp-connector/)
- [x] Write some brief documentation about the example
- [ ] Create user stories for any missing features needed to implement this example
```[tasklist]
### Tasks
- [x] Install PowerShell 7 in the VM
- [x] Install JVM in the VM
- [x] Install SHIR in the VM
- [x] Install SAP NCo in the VM
- [x] Install On-Premises Data Gateway in the VM
```
